"""Validation of the public mink differential-IK fallback on the G1 MJCF.

Drives 100 synthetic reachable frames (smooth SEW trajectories generated by
MuJoCo FK of feasible joint trajectories) and checks:

  * wrist position tracking error < 10 mm mean / 25 mm max after warmup,
  * outputs well-shaped ((7,), (7,), (3,)), finite, hands None, gripper
    pass-through,
  * frozen groups (floating base, legs) never move,
  * engaged=False freezes goals (all-None output, internal state untouched),
  * reset() re-seeds the configuration,
  * resolve_session returns MinkFallbackSession in a subprocess where
    geo_kin / geo_kin_ref imports are poisoned, and raises a clear error
    when model_xml is missing.
"""

import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

mujoco = pytest.importorskip("mujoco")
pytest.importorskip("mink")

from geo_kin_core.fallback import MinkFallbackSession
from geo_kin_core.fallback.presets import G1_SIDES
from geo_kin_core.types import RetargetFrame, SEWPose

G1_ASSETS = Path(
    os.environ.get(
        "G1_TELEOP_ASSETS", "/home/chuizhengk/workspaces/g1_teleop/g1_teleop/assets"
    )
)
G1_XML = G1_ASSETS / "g1_29dof" / "g1_29dof.xml"

pytestmark = pytest.mark.skipif(
    not G1_XML.exists(), reason=f"G1 MJCF not found at {G1_XML}"
)

N_FRAMES = 100
WARMUP = 10
MEAN_TOL_MM = 10.0
MAX_TOL_MM = 25.0

# Comfortable elbows-forward center pose (within limits, away from singularity).
Q_CENTER_RIGHT = np.array([0.30, -0.30, 0.00, 0.90, 0.00, 0.00, 0.00])
Q_CENTER_LEFT = np.array([0.30, 0.30, 0.00, 0.90, 0.00, 0.00, 0.00])
# Per-joint sinusoid amplitudes (rad) / frequencies (cycles over the trajectory).
AMPL = np.array([0.35, 0.20, 0.25, 0.30, 0.30, 0.20, 0.25])
FREQ = np.array([1.0, 2.0, 1.5, 1.0, 2.5, 2.0, 1.5])
PHASE = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0])


@pytest.fixture(scope="module")
def fk():
    """Independent MuJoCo FK context (model, data) for target gen + checking."""
    model = mujoco.MjModel.from_xml_path(str(G1_XML))
    return model, mujoco.MjData(model)


def _adr(model, joints):
    return np.array([model.jnt_qposadr[model.joint(n).id] for n in joints], dtype=int)


@pytest.fixture(scope="module")
def addrs(fk):
    model, _ = fk
    return {
        "right": _adr(model, G1_SIDES["right"]["joints"]),
        "left": _adr(model, G1_SIDES["left"]["joints"]),
        "torso": _adr(model, G1_SIDES["torso"]["joints"]),
    }


def _fk_wrists(fk, addrs, q_right, q_left, q_torso=None):
    """FK -> per-side (wrist pos, wrist R, shoulder pos, elbow pos)."""
    model, data = fk
    data.qpos[:] = model.qpos0
    data.qpos[addrs["right"]] = q_right
    data.qpos[addrs["left"]] = q_left
    if q_torso is not None:
        data.qpos[addrs["torso"]] = q_torso
    mujoco.mj_forward(model, data)
    out = {}
    for side in ("right", "left"):
        wrist = data.body(f"{side}_wrist_yaw_link")
        out[side] = (
            wrist.xpos.copy(),
            wrist.xmat.copy().reshape(3, 3),
            data.body(f"{side}_shoulder_pitch_link").xpos.copy(),
            data.body(f"{side}_elbow_link").xpos.copy(),
        )
    return out


def _synthetic_frames(fk, addrs):
    """100 smooth reachable SEW frames from sinusoidal joint trajectories."""
    frames, targets = [], []
    t_grid = np.linspace(0.0, 1.0, N_FRAMES)
    for t in t_grid:
        wave = np.sin(2.0 * np.pi * FREQ * t + PHASE)
        q_r = Q_CENTER_RIGHT + AMPL * wave
        q_l = Q_CENTER_LEFT + AMPL * wave[::-1]
        pose = _fk_wrists(fk, addrs, q_r, q_l)
        (W_r, R_r, S_r, E_r) = pose["right"]
        (W_l, R_l, S_l, E_l) = pose["left"]
        frames.append(
            RetargetFrame(
                right_sew=SEWPose(S=S_r, E=E_r, W=W_r, R_world_wrist=R_r),
                left_sew=SEWPose(S=S_l, E=E_l, W=W_l, R_world_wrist=R_l),
                R_lower_upper=np.eye(3),
                right_gripper_val=0.25,
                left_gripper_val=0.75,
            )
        )
        targets.append({"right": W_r, "left": W_l})
    return frames, targets


@pytest.fixture(scope="module")
def tracked(fk, addrs):
    """Run the 100-frame trajectory once; share results across assertions."""
    frames, targets = _synthetic_frames(fk, addrs)
    sess = MinkFallbackSession.from_preset("g1", model_xml=G1_XML)
    sess.reset(q_init_right=Q_CENTER_RIGHT, q_init_left=Q_CENTER_LEFT)

    outputs, errors_mm = [], {"right": [], "left": []}
    for frame, tgt in zip(frames, targets):
        out = sess.solve(frame, engaged=True)
        outputs.append(out)
        # Independent FK check of the emitted goals against the commanded W.
        pose = _fk_wrists(fk, addrs, out.q_goal_right, out.q_goal_left, out.q_goal_torso)
        for side in ("right", "left"):
            errors_mm[side].append(1e3 * np.linalg.norm(pose[side][0] - tgt[side]))
    return sess, frames, outputs, {k: np.array(v) for k, v in errors_mm.items()}


def test_wrist_tracking_error(tracked):
    _, _, _, errors_mm = tracked
    for side in ("right", "left"):
        post = errors_mm[side][WARMUP:]
        mean_err, max_err = float(post.mean()), float(post.max())
        print(f"\n[{side}] wrist tracking after warmup: mean {mean_err:.3f} mm, "
              f"max {max_err:.3f} mm (n={post.size})")
        assert mean_err < MEAN_TOL_MM, f"{side} mean error {mean_err:.2f} mm >= {MEAN_TOL_MM} mm"
        assert max_err < MAX_TOL_MM, f"{side} max error {max_err:.2f} mm >= {MAX_TOL_MM} mm"


def test_outputs_well_shaped_and_finite(tracked):
    _, frames, outputs, _ = tracked
    for frame, out in zip(frames, outputs):
        assert out.q_goal_right.shape == (7,)
        assert out.q_goal_left.shape == (7,)
        assert out.q_goal_torso.shape == (3,)
        assert np.all(np.isfinite(out.q_goal_right))
        assert np.all(np.isfinite(out.q_goal_left))
        assert np.all(np.isfinite(out.q_goal_torso))
        # No hand IK in the public fallback; grippers pass through.
        assert out.q_goal_right_hand is None
        assert out.q_goal_left_hand is None
        assert out.q_goal_right_leg is None
        assert out.q_goal_left_leg is None
        assert out.right_gripper_val == frame.right_gripper_val
        assert out.left_gripper_val == frame.left_gripper_val


def test_joint_limits_respected(tracked, fk, addrs):
    model, _ = fk
    _, _, outputs, _ = tracked
    for side, key in (("right", "q_goal_right"), ("left", "q_goal_left")):
        ranges = np.array([model.jnt_range[model.joint(n).id]
                           for n in G1_SIDES[side]["joints"]])
        lo, hi = ranges[:, 0], ranges[:, 1]
        for out in outputs:
            q = getattr(out, key)
            assert np.all(q >= lo - 1e-6) and np.all(q <= hi + 1e-6)


def test_frozen_groups_never_move(tracked, fk):
    """The floating base and legs must stay exactly at the home configuration."""
    model, _ = fk
    sess, _, _, _ = tracked
    qpos = sess._configuration.data.qpos
    leg_joints = [n for n in
                  ("left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint",
                   "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
                   "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint",
                   "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint")]
    leg_adr = _adr(model, leg_joints)
    np.testing.assert_allclose(qpos[leg_adr], 0.0, atol=1e-12)
    np.testing.assert_allclose(qpos[:7], sess._q_home[:7], atol=1e-12)  # free base


def test_disengaged_freezes_goals(tracked):
    sess, frames, _, _ = tracked
    snapshot = sess._configuration.data.qpos.copy()
    out = sess.solve(frames[0], engaged=False)
    assert out.q_goal_right is None
    assert out.q_goal_left is None
    assert out.q_goal_torso is None
    assert out.q_goal_right_hand is None and out.q_goal_left_hand is None
    np.testing.assert_array_equal(sess._configuration.data.qpos, snapshot)


def test_reset_reseeds_configuration(fk):
    sess = MinkFallbackSession.from_preset("g1", model_xml=G1_XML)
    q_r = np.full(7, 0.2)
    q_l = np.full(7, -0.1)
    sess.reset(q_init_right=q_r, q_init_left=q_l)
    qpos = sess._configuration.data.qpos
    np.testing.assert_allclose(qpos[sess._arm_qposadr["right"]], q_r)
    np.testing.assert_allclose(qpos[sess._arm_qposadr["left"]], q_l)
    # reset() without inits returns to the model home configuration.
    sess.reset()
    np.testing.assert_array_equal(sess._configuration.data.qpos, sess._q_home)


_SUBPROCESS_SCRIPT = r"""
import sys
# Poison the licensed wheel and the private reference so resolve_session must
# fall back to the public mink solver.
sys.modules["geo_kin"] = None
sys.modules["geo_kin_ref"] = None

from geo_kin_core.session import resolve_session

# 1) Without model_xml the fallback must raise a clear, actionable error.
try:
    resolve_session("g1")
except ValueError as exc:
    msg = str(exc)
    assert "model_xml" in msg and "MJCF" in msg, "unhelpful error: " + msg
else:
    raise AssertionError("resolve_session without model_xml should have raised")

# 2) With model_xml it must return the mink fallback session.
sess = resolve_session("g1", model_xml=@XML@)
print("RESOLVED:" + type(sess).__name__)
"""


def test_resolve_session_falls_back_in_poisoned_subprocess():
    script = _SUBPROCESS_SCRIPT.replace("@XML@", repr(str(G1_XML)))
    proc = subprocess.run(
        [sys.executable, "-c", script], capture_output=True, text=True, timeout=180
    )
    assert proc.returncode == 0, f"subprocess failed:\n{proc.stdout}\n{proc.stderr}"
    assert "RESOLVED:MinkFallbackSession" in proc.stdout
